services:
  postgres:
    image: postgres:16
    container_name: leaderboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    env_file: env.docker
    container_name: leaderboard-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      #DB_URL: postgres://postgres:postgres@postgres:5432/leaderboard
      #DB_URL: ${DB_URL}
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
